name: Deploy Static Website

on:
  push:
    branches:
      - main  # deploy only on main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Copy files via SCP
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          port: 22
          source: "build/*"      # your local folder with website files
          target: ${{ secrets.EC2_TARGET_PATH }}
          strip_components: 1
          overwrite: true
