name: Deploy Static Website

on:
  push:
    branches:
      - main  # deploy only when main branch is updated

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # 2️⃣ Upload files via SCP
      - name: Deploy to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          port: 22
          source: "build/*"              # local folder with website files
          target: ${{ secrets.EC2_TARGET_PATH }}
          strip_components: 1
          overwrite: true
          debug: true                    # optional, shows detailed logs

      # 3️⃣ (Optional) Restart Nginx after deploy
      - name: Restart Nginx
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          port: 22
          script: |
            sudo systemctl restart nginx
            echo "Nginx restarted!"
